[Added] [BEL-3906] was added support to get base url given a environment name
belvo-finance/belvo-python pull request #119
Opened 2021-06-29 03:31 UTC by benitocas88

:question: What
---

- It's possible pass an environment name to `Client` to get base url

`client = Client('secret-id', 'secret-password', 'sandbox|production|development')`

:speech_balloon: Why
---

- It's easier and friendly pass an environment name avoiding an extra path for base url

 
https://belvoteam.atlassian.net/browse/BEL-3906

2021-06-29 13:20 UTC, menecio requested changes

2021-06-29 13:20 UTC, menecio commented on belvo/client.py
> +            message = (
@benitocas88 url is optional because you can provision the value thru the environment variable. This aims to mimic the same way AWS allows you to prepare your env with all credentials and configurations without needing to modify your imeplementation

2021-06-29 13:42 UTC, benitocas88 commented on belvo/client.py
> +            message = (
Ok, I understand about the url optional and the same way AWS allows us to prepare the env, but I don't catch what should be the change here. Maybe revert to the original message? @menecio

2021-06-29 14:18 UTC, menecio commented on belvo/client.py
> +            message = (
Maybe you should translate the environment at L15

2021-06-29 15:08 UTC, anisaoshafi commented on belvo/client.py
> +                "You need provide a valid environment name. "
Since it can be either url or just the env name directly ("sandbox" for example)
```suggestion
                "You need to provide a valid environment."
```

2021-06-29 15:43 UTC, anisaoshafi commented on belvo/client.py
> +    def __init__(self, secret_key_id: str, secret_key_password: str, url: str = "") -> None:
there's no need to change the constructor here. It does the same things, because `URL_ENVIRONMENTS.get(None) = None`. it's same things though

2021-06-29 16:01 UTC, anisaoshafi commented on belvo/client.py
> +    def __init__(self, secret_key_id: str, secret_key_password: str, url: str = "") -> None:
since the user can pass the environment by **name** ("sandbox") or by **url** (https://sandbox.belvo.com), can we rename `url` param to `environment`? 
@menecio would this break  any customer implementation? AFAIK the Client is initiated like this:
`Client("Secret Key ID", "Secret Key PASSWORD", "https://sandbox.belvo.com")`. 
But can it also be initiated like this? If yes, it can break sth & we can ignore this.
`Client("Secret Key ID", "Secret Key PASSWORD", url="https://sandbox.belvo.com")`
```suggestion
    def __init__(self, secret_key_id: str, secret_key_password: str, environment: str = "") -> None:
```

2021-06-29 16:07 UTC, benitocas88 commented on belvo/client.py
> +    def __init__(self, secret_key_id: str, secret_key_password: str, url: str = "") -> None:
I think we should consider some users use `url="https://..."`. BTW, i found the solution for my previos comment about linting, 
```
def url_resolver(url: Optional[str]):
    ....
```

2021-06-29 16:09 UTC, anisaoshafi commented on belvo/client.py
> +    def __init__(self, secret_key_id: str, secret_key_password: str, url: str = "") -> None:
then you can dismiss my previous comment about renaming `url` to `environment`.
great Beni 💪🏼

2021-06-29 18:24 UTC, benitocas88 commented on belvo/client.py
> +            env = UrlEnvironments.get_url(url)
On my perspective: 
I took the decision evaluate the `value` passed in constructor `Client("secret", "password", "https://...|production")` instead to pass a new argument (`environment: str = None`) in constructor; the goal is be transparent for current users and according the ticket description we'll update our docs changing the code samples with this new way m`Client("secret", "password", "production")`. @menecio

2021-06-30 14:30 UTC, anisaoshafi approved these changes
lgtm 💪🏼 
just remember to keep the error message consistent in all libraries :)

2021-07-02 06:43 UTC, shekodn commented on tests/test_client.py
> +def test_client_url_from_environ(responses, environment, expected_url):
```suggestion
def test_client_url_from_environment(responses, environment, expected_url):
```

2021-07-02 06:47 UTC, shekodn commented on tests/test_client.py
> +def test_client_url_from_environ(responses, environment, expected_url):
I would try to be a little bit more verbose here: eg. test_client_url_is_ok_when_receiving_an_environment

2021-07-02 06:50 UTC, shekodn commented on belvo/enums.py
> +@unique
Question: Why do we need this decorator? Is it to be more idiomatic? 

https://stackoverflow.com/questions/56139511/what-does-the-unique-decorator-do-in-python

2021-07-02 12:51 UTC, benitocas88 commented on belvo/enums.py
> +@unique
It's to prevent values are not repeated
https://docs.python.org/3/library/enum.html#ensuring-unique-enumeration-values

2021-07-02 13:56 UTC, anisaoshafi approved these changes

2021-07-02 13:57 UTC, gingrassia approved these changes

2021-07-02 15:41 UTC, merged