[Added] [BEL-7797] Add support for risk insights endpoint
belvo-finance/belvo-python pull request #136
Opened 2021-11-18 10:38 UTC by jordisoler

:question: What
---
- Add support for `/api/risk-insights/` endpoint

2021-11-18 15:10 UTC, maria-ribalta requested changes

2021-11-18 15:10 UTC, maria-ribalta commented on docs/resources.md
> +risk_insights = client.RoskInsights.create(
typo

2021-11-18 15:10 UTC, maria-ribalta commented on docs/resources.md
> +If no filters are provided, you will get all `RiskInsight` objects that you have registered.
shouldn't this be `RiskInsights` too?

2021-11-18 15:53 UTC, maria-ribalta approved these changes

2021-11-19 09:28 UTC, AlbertMaristany approved these changes

2021-11-19 10:01 UTC, merged