Improvements in the resources
belvo-finance/belvo-python pull request #79
Opened 2020-10-29 22:07 UTC by matheuslins

:question: What
---

1. Changed the organization of the resources
2. Changed some parts of code

:speech_balloon: Why
---

> 1.

- With this organization, you can add one more class just by creating a new file and writing that in isolation.
- It's easier to find where is what you are looking for
- It's easier to maintain

> 2.

**before**

*Links class*

```python

if access_mode is None:
    access_mode = AccessMode.SINGLE

```
**suggestion**

```python
access_mode: AccessMode = AccessMode.SINGLE,
```

**before**

*Transactions class*

```python
if date_to is None:
    date_to = date.today().isoformat()
```

**suggestion**

```python
date_to = date_to or date.today().isoformat()
```

**before**

*Balances class*

```python
if date_to is None:
    date_to = date.today().isoformat()
```

**suggestion**

```python
date_to = date_to or date.today().isoformat()
```

**before**

*TaxReturns class*

```python
if year_to is None:
    year_to = date.today().year
```

**suggestion**

```python
year_to = year_to or date.today().year
```

2020-10-30 08:45 UTC, menecio requested changes
Thank you very much for this contribution!

 I have added some remarks that should be addressed to have this one ready for merge.

Cheers

2020-10-30 08:45 UTC, menecio commented on belvo/client.py
> +from .resources import *
Using `import *` is something you should avoid, as you can end up shadowing objects in your code without knowing. 
Also remember the Zen of Python: "Explicit is better than Implicit", one way to avoid this is to 
```python
from . import resources`

foo = resources.Institutions
```

2020-10-30 08:45 UTC, menecio commented on tests/test_resources.py
> +from belvo.resources import *
Same as before

2020-10-30 08:45 UTC, menecio commented on belvo/base_resource.py
> +from typing import Dict, Generator, List, Union
Would be better to have this as `bevo/resources/base.py` as the goal here is to make good use of namespaces to organize the code.

2020-10-30 16:59 UTC, matheuslins commented on belvo/client.py
> +from .resources import *
Great! I completely agree :D

2020-11-02 11:48 UTC, menecio commented
@matheuslins I updated our dependencies and explicitly declared which python version `black` should target, this should solve your error in travis, could you try to rebase to our latest `master` ?

2020-11-02 14:35 UTC, matheuslins commented
@menecio I updated my branch, but I think didn't work.

2020-11-02 14:41 UTC, matheuslins commented
@menecio There are many errors like this: `ERROR: /home/travis/build/belvo-finance/belvo-python/belvo/client.py Imports are incorrectly sorted.`

Do you think that the reason why the build failed?

2020-11-02 14:59 UTC, menecio commented
> @menecio There are many errors like this: `ERROR: /home/travis/build/belvo-finance/belvo-python/belvo/client.py Imports are incorrectly sorted.`
> 
> Do you think that the reason why the build failed?

Yes, there is a make rule that will help you to sort it out `make linting fix=yes`, I've also taken your commits into a separated branch and applied the fixes at #80 

If you prefer we can continue with that PR

2020-11-02 15:47 UTC, closed without merging

2020-11-03 13:06 UTC, matheuslins commented
@menecio Hmm, got it! Great, thanks!